# -----------------------------------------------------------------------------
# EKS GitOps Blueprint — observability: kube-prometheus-stack
# Author: Nour El Houda Bouajila (https://github.com/nourhb)
#
# Installs Prometheus (metrics collection), Grafana (dashboards) and
# Alertmanager (alert routing) via the kube-prometheus-stack chart.
# Prometheus and Grafana persist on gp3 EBS volumes so history survives
# pod restarts. A gp3 StorageClass is created because the EBS CSI default
# is still gp2.
# -----------------------------------------------------------------------------

resource "kubernetes_storage_class" "gp3" {
  metadata {
    name = "gp3"
  }

  storage_provisioner    = "ebs.csi.aws.com"
  reclaim_policy         = "Delete"
  volume_binding_mode    = "WaitForFirstConsumer"
  allow_volume_expansion = true

  parameters = {
    type      = "gp3"
    encrypted = "true"
  }

  depends_on = [aws_eks_addon.ebs_csi]
}

resource "random_password" "grafana_admin" {
  length  = 24
  special = false
}

resource "helm_release" "monitoring" {
  name             = "kube-prometheus-stack"
  repository       = "https://prometheus-community.github.io/helm-charts"
  chart            = "kube-prometheus-stack"
  version          = var.monitoring_chart_version
  namespace        = "monitoring"
  create_namespace = true

  # Prometheus: 15d retention on a 50Gi gp3 volume.
  set {
    name  = "prometheus.prometheusSpec.retention"
    value = "15d"
  }

  set {
    name  = "prometheus.prometheusSpec.storageSpec.volumeClaimTemplate.spec.storageClassName"
    value = kubernetes_storage_class.gp3.metadata[0].name
  }

  set {
    name  = "prometheus.prometheusSpec.storageSpec.volumeClaimTemplate.spec.accessModes[0]"
    value = "ReadWriteOnce"
  }

  set {
    name  = "prometheus.prometheusSpec.storageSpec.volumeClaimTemplate.spec.resources.requests.storage"
    value = "50Gi"
  }

  # Grafana: persistence on gp3, admin password generated by Terraform.
  set {
    name  = "grafana.persistence.enabled"
    value = "true"
  }

  set {
    name  = "grafana.persistence.storageClassName"
    value = kubernetes_storage_class.gp3.metadata[0].name
  }

  set {
    name  = "grafana.persistence.size"
    value = "10Gi"
  }

  set {
    name  = "grafana.adminPassword"
    value = random_password.grafana_admin.result
  }

  # Lean defaults for a demo cluster: single replicas.
  set {
    name  = "prometheus.prometheusSpec.replicas"
    value = "1"
  }

  set {
    name  = "alertmanager.alertmanagerSpec.replicas"
    value = "1"
  }

  depends_on = [aws_eks_node_group.default]
}
